name: environment
channels:
  - plotly
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - jinja2=3.1.2=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.1.2=py311h06a4308_0
  - plotly=5.22.0=py_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - python=3.11.4=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tenacity=8.2.2=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py311h5eee18b_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - anndata==0.10.8
      - array-api-compat==1.7.1
      - asciitree==0.3.3
      - asttokens==2.4.1
      - comm==0.2.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==0.29.36
      - debugpy==1.8.0
      - defusedxml==0.7.1
      - executing==2.0.1
      - fasteners==0.19
      - fastlbp-imbg==0.1.1
      - fire==0.5.0
      - fonttools==4.45.0
      - fsspec==2023.10.0
      - h5py==3.11.0
      - hdbscan==0.8.33
      - igraph==0.11.6
      - imagecodecs==2023.9.18
      - imageio==2.33.0
      - ipykernel==6.27.0
      - ipython==8.17.2
      - jedi==0.19.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - llvmlite==0.41.1
      - lxml==4.9.3
      - matplotlib==3.8.2
      - memory-profiler==0.61.0
      - natsort==8.4.0
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - numba==0.58.1
      - numcodecs==0.12.1
      - numpy==1.26.2
      - packaging==23.2
      - pandas==2.1.3
      - patsy==0.5.6
      - pillow==10.1.0
      - platformdirs==4.0.0
      - prompt-toolkit==3.0.41
      - psutil==5.9.6
      - pygments==2.17.2
      - pynndescent==0.5.11
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - scanpy==1.10.2
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - session-info==1.0.0
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - termcolor==2.3.0
      - textalloc==0.0.11
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tiffslide==2.4.0
      - tqdm==4.66.1
      - traitlets==5.13.0
      - typing-extensions==4.10.0
      - tzdata==2023.3
      - umap-learn==0.5.5
      - wcwidth==0.2.12
      - zarr==2.16.1
